import { Brand } from './brand';

export const Brands: Brand[] = [
  { Name: 'Acura'},
  { Name: 'Alfa Romeo'},
  { Name: 'Aston Martin'},
  { Name: 'Audi'},
  { Name: 'Bentley'},
  { Name: 'BMW'},
  { Name: 'Buick'},
  { Name: 'Cadillac'},
  { Name: 'Chevrolet'},
  { Name: 'Chrysler'},
  { Name: 'Daewoo'},
  { Name: 'Daihatsu'},
  { Name: 'Dodge'},
  { Name: 'Ferrari'},
  { Name: 'Fiat'},
  { Name: 'Fisker'},
  { Name: 'Ford'},
  { Name: 'GMC'},
  { Name: 'Honda'},
  { Name: 'Hummer'},
  { Name: 'Hyundai'},
  { Name: 'Infiniti'},
  { Name: 'Isuzu'},
  { Name: 'Iveco'},
  { Name: 'Jaguar'},
  { Name: 'Jeep'},
  { Name: 'Kia'},
  { Name: 'Lamborghini'},
  { Name: 'Lancia'},
  { Name: 'Land Rover'},
  { Name: 'Lexus'},
  { Name: 'Lincoln'},
  { Name: 'Maserati'},
  { Name: 'Mazda'},
  { Name: 'Mercedes-Benz'},
  { Name: 'Mercury'},
  { Name: 'MG'},
  { Name: 'Mini'},
  { Name: 'Mitsubishi'},
  { Name: 'Nissan'},
  { Name: 'Oldsmobile'},
  { Name: 'Opel'},
  { Name: 'Peugeot'},
  { Name: 'Plymouth'},
  { Name: 'Pontiac'},
  { Name: 'Porsche'},
  { Name: 'Rolls Royce'},
  { Name: 'Rover'},
  { Name: 'Saab'},
  { Name: 'Saturn'},
  { Name: 'Seat'},
  { Name: 'Smart'},
  { Name: 'Subaru'},
  { Name: 'Suzuki'},
  { Name: 'Tesla'},
  { Name: 'Think'},
  { Name: 'Toyota'},
  { Name: 'Volkswagen'},
  { Name: 'Volvo'}
];